version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: "always"
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
      - METRICS_STORAGE_TYPE
    networks:
      - jaeger-networks


networks:
  jaeger-networks: