FROM rabbitmq:3.12.7-management

# RUN rabbitmq-plugins enable rabbitmq_stomp
# RUN rabbitmq-plugins enable rabbitmq_web_stomp_examples
RUN rabbitmq-plugins enable rabbitmq_mqtt
RUN rabbitmq-plugins enable rabbitmq_web_mqtt_examples