version: '3.7'

services:
  case-gateway:
    image: dockerhub.coj.intra/case-gateway:1.1
    restart: "always"
    # ports:
    # - "9003:9003"  
    # >> scaling  
    # >>  docker-compose up -d --scale case-gateway=2
    ports:  
      - target: 9003 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.case-gateway.rule=(Host(`coj-x.coj.intra`) && Path(`/labor`)) || PathPrefix(`/labor`)"
      
      - "traefik.http.routers.case-gateway.middlewares=regEx,apiKeyLB,forwardedHeaders"
      - "traefik.http.middlewares.regEx.replacepathregex.regex=^/labor(.*)"
      - "traefik.http.middlewares.regEx.replacepathregex.replacement=/api/v1forwards$${1}"

      #API-KEY AUTHEN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
      - "traefik.http.middlewares.apiKeyLB.plugin.traefik-api-key-middleware.authenticationHeader=true"
      - "traefik.http.middlewares.apiKeyLB.plugin.traefik-api-key-middleware.authenticationheaderName=X-API-KEY"
      - "traefik.http.middlewares.apiKeyLB.plugin.traefik-api-key-middleware.bearerHeader=true"
      - "traefik.http.middlewares.apiKeyLB.plugin.traefik-api-key-middleware.bearerHeaderName=Authorization"
      - "traefik.http.middlewares.apiKeyLB.plugin.traefik-api-key-middleware.removeHeadersOnSuccess=true"
      - "traefik.http.middlewares.apiKeyLB.plugin.traefik-api-key-middleware.keys=ff08048b-ebf9-4dca-b3bd-2935738dd108"  

      # ADD HEADER# Use the forwarded middleware
      - "traefik.http.middlewares.forwardedHeaders.headers.customrequestheaders.system-id=1"
      - "traefik.http.middlewares.forwardedHeaders.headers.customrequestheaders.system-code=LABOR"
      - "traefik.http.middlewares.forwardedHeaders.headers.customrequestheaders.*=true" # Attach the middleware to your app
    networks:
        - traefik-networks

  #sหมายบังคับคดี
  exwar-gateway:
    image: dockerhub.coj.intra/case-gateway:1.1
    restart: "always"
    # ports:
    # - "9003:9003"  
    # >> scaling  
    # >>  docker-compose up -d --scale case-gateway=2
    ports:    
      - target: 9003  
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.exwar-gateway.rule=Host(`exwar-gateway.docker.localhost`) || Host(`coj-x.coj.intra`) ||  PathPrefix(`/exwar`)"
      - "traefik.http.routers.exwar-gateway.rule=(Host(`coj-x.coj.intra`) && Path(`/exwar`)) || PathPrefix(`/exwar`)"
      - "traefik.http.routers.exwar-gateway.middlewares=regExEW,apiKeyEW,forwardedHeadersEW"
      - "traefik.http.middlewares.regExEW.replacepathregex.regex=^/exwar(.*)"
      - "traefik.http.middlewares.regExEW.replacepathregex.replacement=/api/v1/forwards$${1}"

      #API-KEY AUTHEN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
      - "traefik.http.middlewares.apiKeyEW.plugin.traefik-api-key-middleware.authenticationHeader=true"
      - "traefik.http.middlewares.apiKeyEW.plugin.traefik-api-key-middleware.authenticationheaderName=X-API-KEY"
      - "traefik.http.middlewares.apiKeyEW.plugin.traefik-api-key-middleware.bearerHeader=true"
      - "traefik.http.middlewares.apiKeyEW.plugin.traefik-api-key-middleware.bearerHeaderName=Authorization"
      - "traefik.http.middlewares.apiKeyEW.plugin.traefik-api-key-middleware.removeHeadersOnSuccess=true"
      - "traefik.http.middlewares.apiKeyEW.plugin.traefik-api-key-middleware.keys=b8e471ed-9f78-4b0e-9f0d-ba3c9339f3b6"  

      # ADD HEADER# Use the forwarded middleware
      - "traefik.http.middlewares.forwardedHeadersEW.headers.customrequestheaders.system-id=2"
      - "traefik.http.middlewares.forwardedHeadersEW.headers.customrequestheaders.system-code=EXWAR"
      - "traefik.http.middlewares.forwardedHeadersEW.headers.customrequestheaders.*=true" # Attach the middleware to your app
    networks:
        - traefik-networks
networks:
  traefik-networks:
    driver: bridge