version: '3'

services:
  harbor:
    image: goharbor/harbor-core:v2.8.2
    hostname: harbor
    container_name: harbor
    restart: always
    ports:
      - 5000:80
      - 443:443
    volumes:
      - /data/certs:/harbor_cust_cert
      - /data/database:/var/lib/postgresql
      - /data/registry:/harbor_registry
      - /data/jobservice:/var/lib/jobservice
      - /data/clair:/clair_config
      - /data/redis:/var/lib/redis
      - /data/chartmuseum:/charts
    environment:
      - HARBOR_ADMIN_PASSWORD=admin
      - HARBOR_REGISTRY_HTTP_SECRET=harbor@coj#2023
    depends_on:
      - postgresql
      - redis
      - clair
      - chartmuseum

  postgresql:
    image: postgres:13
    restart: always
    volumes:
      - /data/database:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=registry

  redis:
    image: redis:6.0.20-alpine
    restart: always
    volumes:
      - /data/redis:/data

  clair:
    image: goharbor/clair-photon:v1.10.18
    restart: always
    volumes:
      - /data/clair:/clair_config
    depends_on:
      - postgresql

  chartmuseum:
    image: goharbor/chartmuseum-photon:v1.10.18
    restart: always
    volumes:
      - /data/chartmuseum:/charts

